finish
/clear
/filname,gene_truss

!!输入数据
*DIM,INPUTDATA,array,10,1
*VREAD,INPUTDATA,D:\SOFTWARE\ANSYS\truss_10\input,txt,,IJK,
(1f6.0)
m1=INPUTDATA(1)
m2=INPUTDATA(2)
m3=INPUTDATA(3)
m4=INPUTDATA(4)
m5=INPUTDATA(5)
m6=INPUTDATA(6)
m7=INPUTDATA(7)
m8=INPUTDATA(8)
m9=INPUTDATA(9)
m10=INPUTDATA(10)


!!参数输入
/prep7
!!材料特性
Ex=1e7												!!弹性模量
Nu=0.3												!!泊松比
Dens=0.1											!!材料密度


!!定义结构
/prep7

!!定义截面
et,1,link180
mp,ex,1,Ex
mp,nuxy,1,Nu   									
mp,dens,1,Dens
sectype,1,link,CSOLID							
secdata,1.62
sectype,2,link,CSOLID							
secdata,1.8
sectype,3,link,CSOLID							
secdata,1.99
sectype,4,link,CSOLID							
secdata,2.13
sectype,5,link,CSOLID							
secdata,2.38
sectype,6,link,CSOLID							
secdata,2.62
sectype,7,link,CSOLID							
secdata,2.63
sectype,8,link,CSOLID							
secdata,2.88
sectype,9,link,CSOLID							
secdata,2.93
sectype,10,link,CSOLID							
secdata,3.09
sectype,11,link,CSOLID							
secdata,3.13
sectype,12,link,CSOLID							
secdata,3.38
sectype,13,link,CSOLID							
secdata,3.47
sectype,14,link,CSOLID							
secdata,3.55
sectype,15,link,CSOLID							
secdata,3.63
sectype,16,link,CSOLID							
secdata,3.84
sectype,17,link,CSOLID							
secdata,3.87
sectype,18,link,CSOLID							
secdata,3.88
sectype,19,link,CSOLID							
secdata,4.18
sectype,20,link,CSOLID							
secdata,4.22
sectype,21,link,CSOLID							
secdata,4.49
sectype,22,link,CSOLID							
secdata,4.59
sectype,23,link,CSOLID							
secdata,4.8
sectype,24,link,CSOLID							
secdata,4.97
sectype,25,link,CSOLID							
secdata,5.12
sectype,26,link,CSOLID							
secdata,5.74
sectype,27,link,CSOLID							
secdata,7.22
sectype,28,link,CSOLID							
secdata,7.97
sectype,29,link,CSOLID							
secdata,11.5
sectype,30,link,CSOLID							
secdata,13.5
sectype,31,link,CSOLID							
secdata,13.9
sectype,32,link,CSOLID							
secdata,14.2
sectype,33,link,CSOLID							
secdata,15.5
sectype,34,link,CSOLID							
secdata,16
sectype,35,link,CSOLID							
secdata,16.9
sectype,36,link,CSOLID							
secdata,18.8
sectype,37,link,CSOLID							
secdata,19.9
sectype,38,link,CSOLID							
secdata,22
sectype,39,link,CSOLID							
secdata,22.9
sectype,40,link,CSOLID							
secdata,26.5
sectype,41,link,CSOLID							
secdata,30
sectype,42,link,CSOLID							
secdata,33.5
sectype,43,link,CSOLID							
secdata,35
sectype,44,link,CSOLID							
secdata,37.5
sectype,45,link,CSOLID							
secdata,40
sectype,46,link,CSOLID							
secdata,42.5
sectype,47,link,CSOLID							
secdata,45
sectype,48,link,CSOLID							
secdata,47.5
sectype,49,link,CSOLID							
secdata,50
sectype,50,link,CSOLID							
secdata,52.5
sectype,51,link,CSOLID							
secdata,55
sectype,52,link,CSOLID							
secdata,57.5
sectype,53,link,CSOLID							
secdata,60
sectype,54,link,CSOLID							
secdata,62.5
sectype,55,link,CSOLID							
secdata,65
sectype,56,link,CSOLID							
secdata,67.5
sectype,57,link,CSOLID							
secdata,70
sectype,58,link,CSOLID							
secdata,72.5
sectype,59,link,CSOLID							
secdata,75
sectype,60,link,CSOLID							
secdata,77.5
sectype,61,link,CSOLID							
secdata,80
sectype,62,link,CSOLID							
secdata,82.5
sectype,63,link,CSOLID							
secdata,85
sectype,64,link,CSOLID							
secdata,87.5
sectype,65,link,CSOLID							
secdata,90



!!定义节点
N,1,720,360,0
N,2,720,0,0
N,3,360,360,0
N,4,360,0,0
N,5,0,360,0
N,6,0,0,0

!!定义单元
type,1
mat,1
secnum,m1
e,5,3
secnum,m2
e,3,1
secnum,m3
e,6,4
secnum,m4
e,4,2
secnum,m5
e,4,3
secnum,m6
e,2,1
secnum,m7
e,5,4
secnum,m8
e,6,3
secnum,m9
e,3,2
secnum,m10
e,1,4

!!施加约束
nsel,s,node,,5
nsel,a,node,,6
d,all,ux,0
d,all,uy,0
d,all,uz,0

!!施加荷载
ACEL,,,9.8
nsel,s,node,,2
nsel,a,node,,4
f,all,fy,-1e5
finish

!!!首先进行静力分析
/solu 
allsel，all
antype,0
pstres,on         					!!打开预应力开关
solve 
finish                		 	!!结束当前求解

/post1
NSORT,U,Y,0,0	
*get,y_max,SORT,0,MAX
*get,y_min,SORT,0,MIN


set,1,last           
allsel,all
Etable,STRESS,LS,2  						!采用单元获取内力
Esort,etab,STRESS,0,0   				!对单元表进行排序
*get,stress_max,sort,0,max    !最大值获取
*get,stress_min,sort,0,min    !最大值获取

*cfopen,output,txt,,
*vwrite,y_max,y_min,stress_max,stress_min
(f10.5,2x,f10.5,2x,e15.6,,2x,e15.6)
*cfclos
finish

